name: AdTechHumor
favicon: null
layout_spectrum: 0.7152164047583938
typography_spectrum: 0.28340485878288746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7948444345965981
  lightness: 0.013496177038177848
  saturation: 0.7019108938984573
  rhythmicContrast: 0.9009787722025067
purpose: []
